# Generated by Django 5.1.5 on 2025-01-18 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_location', models.CharField(help_text='Where are you starting from?', max_length=200, verbose_name='Starting Location')),
                ('finishing_location', models.CharField(help_text='Where are you going?', max_length=200, verbose_name='Finishing Location')),
                ('with_who', models.CharField(help_text='Who are you going with?', max_length=200, verbose_name='Companions')),
                ('time_limit', models.PositiveIntegerField(help_text='Set a timer in minutes for safety.', verbose_name='Time Limit (Minutes)')),
                ('pin_code', models.CharField(help_text='Alphanumeric pin code to confirm arrival or share if not safe.', max_length=10, verbose_name='Pin Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
