# Generated by Django 5.1.5 on 2025-01-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0002_plannedroute_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedroute',
            name='secret_key',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
    ]
